name: Test against PR

on:
  pull_request:

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: false
